"""
Debug Agent提示词构造模块
"""

from typing import Dict, List, Optional
from pathlib import Path


# 技能文档的根目录
SKILL_DIR = Path(__file__).parent.parent.parent / "skills" / "debug-geospatial"


def build_system_prompt() -> str:
    """
    构建智能体系统提示词

    将身份声明与技能文档正文拼接为完整的系统级指令
    """
    identity = (
        "You are a specialized debugging agent for geospatial Python code. "
        "You operate within an automated repair pipeline that iteratively "
        "diagnoses and corrects scripts generated by language models for "
        "spatial analysis tasks. The following guide defines your capabilities, "
        "working procedures, and output conventions."
    )

    skill_content = _load_skill_body()

    return f"{identity}\n\n{skill_content}"


def build_initial_user_message(
    current_code: str,
    current_diagnosis: Optional[Dict] = None,
    error_summary: Optional[str] = None,
    round_num: int = 1,
    max_rounds: int = 3
) -> str:
    """
    构建初始用户消息

    Args:
        current_code: 带行号的当前版本代码
        current_diagnosis: 任务级诊断信息（包含root_cause和patches）
        error_summary: 错误概要（如有先前执行记录）
        round_num: 当前轮次编号
        max_rounds: 最大轮次数

    Returns:
        用户消息文本
    """
    sections = []

    sections.append(f"## Round {round_num} of {max_rounds}\n")

    sections.append("## Current Code (with line numbers)\n")
    sections.append(
        "The following encompasses the entire codebase under investigation. "
        "All line references and patch targets derive from this listing exclusively.\n"
    )
    sections.append("```python")
    sections.append(current_code)
    sections.append("```\n")

    if current_diagnosis:
        sections.append("## Previous Diagnosis\n")
        sections.append(
            "The following captures the complete findings from the prior attempt. "
            "You may refine, correct, or retain any part as warranted by fresh evidence.\n"
        )

        if current_diagnosis.get('root_cause'):
            sections.append(f"**Root Cause Analysis**:\n{current_diagnosis['root_cause']}\n")

        patches = current_diagnosis.get('patches', [])
        if patches:
            sections.append(f"**Patches** ({len(patches)} total):\n")
            for i, patch in enumerate(patches, 1):
                sections.append(f"### Patch {i}")
                sections.append("**Target (from original):**")
                sections.append(f"```python\n{patch.get('target_code', '')}\n```")
                sections.append("**Replacement:**")
                sections.append(f"```python\n{patch.get('replacement_code', '')}\n```\n")

    if error_summary:
        sections.append("## Latest Execution Result\n")
        sections.append(error_summary)
        sections.append("")

    sections.append("## Your Task\n")
    sections.append(
        "Investigate the code and either confirm successful execution "
        "or provide a complete diagnosis with all necessary patches."
    )
    sections.append(
        "\nThe code and patch history presented above are the sole reference "
        "for constructing repairs—no external source files exist."
    )

    return "\n".join(sections)


def format_code_with_line_numbers(code: str, start_line: int = 1) -> str:
    """
    为代码添加行号

    Args:
        code: 原始代码文本
        start_line: 起始行号

    Returns:
        带行号的代码文本
    """
    lines = code.split('\n')
    width = len(str(start_line + len(lines) - 1))

    numbered_lines = []
    for i, line in enumerate(lines, start_line):
        numbered_lines.append(f"{i:>{width}} | {line}")

    return '\n'.join(numbered_lines)


def _load_skill_body() -> str:
    """
    读取SKILL.md并提取正文部分（跳过YAML frontmatter）
    """
    skill_path = SKILL_DIR / "SKILL.md"

    if not skill_path.exists():
        raise FileNotFoundError(f"Skill document not found: {skill_path}")

    content = skill_path.read_text(encoding='utf-8')

    # 跳过YAML frontmatter（两个---之间的内容）
    if content.startswith('---'):
        end_marker = content.find('---', 3)
        if end_marker != -1:
            content = content[end_marker + 3:].strip()

    return content